version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
  versioning-strategy: increase
